### PR TITLE
Add SonarQube

### PR DESCRIPTION
**Pull request by bheuvel**

### CODE REVIEW

**Comment by bheuvel** [comment]
Jenkins has already been updated, yet code not yet committed.
Initial data already visible; https://beta-sonar.mcc.schubergphilis.com/dashboard/index?did=6

**Comment by borisroman** [comment]
@bheuvel Could you check the if the versions aren't defined in Spring Boot already?

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
Only `maven-resources-plugin` is defined in Spring Boot, but this is a higher version.

Also added/corrected test coverage

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Pull request merged**
